## Students' performance analysis

### 1. Students' total score per

In [139]:
# %pip install numpy pandas
import numpy as np
import pandas as pd

subjects = ["maths", "physics", "yoruba", "french"]

students = ["student_1", "student_2", "student_3", "student_4", "student_5",]

studentPerformance = np.array([[80, 40, 60, 45],
                               [75, 45, 60, 23],
                               [85, 50, 62, 35],
                               [75, 44, 54, 43],
                               [88, 45, 65, 23]])



studentPerformance.shape[0]

# Loop through each student (row in the array)
for i in range(studentPerformance.shape[0]):
    student_total = studentPerformance[i, :].sum()
    print(f"{students[i]} has total score: {student_total}")

# studentPerformance.shape[0]

# # Loop through each student (row in the array)
# student_total_score = np.zeros(studentPerformance.shape[0])

# for i in range(studentPerformance.shape[0]):
#     student_total_score[i] = studentPerformance[i, :].sum()
    
# print(f"Student_{i+1} has total score: {student_total_score}")

student_1 has total score: 225
student_2 has total score: 203
student_3 has total score: 232
student_4 has total score: 216
student_5 has total score: 221


In [149]:



for i in range(studentPerformance.shape[1]):
    subject_average = studentPerformance[:, i].sum()
    subject_average = subject_average/4
    print(f"{subjects[i]} average score: {subject_average}")




maths average score: 100.75
physics average score: 56.0
yoruba average score: 75.25
french average score: 42.25


### 2. Weighing by Scalar

In [151]:


# data_1 = studentPerformance[0, :]
# print(data_1)


# result = data_1 * scaler
# print(result)

scaler = [3, 1, 1, 1]

scaled_matrix_1 = np.zeros_like(studentPerformance)

for i in range(studentPerformance.shape[0]):
    data = studentPerformance[i, :]
    scaled_matrix_1[i, :] = data * scaler  

print(scaled_matrix_1)

[[240  40  60  45]
 [225  45  60  23]
 [255  50  62  35]
 [225  44  54  43]
 [264  45  65  23]]


### 3. Weighing to total grades by scaling

In [ ]:
scaler_2 = [0.4, 0.2, 0.3, 0.1]

scaled_matrix_2 = np.zeros_like(scaled_matrix_1)

for i in range(studentPerformance.shape[0]):
    data = scaled_matrix_1[i, :]
    scaled_matrix_2[i, :] = data * scaler_2
    

    

print(scaled_matrix_2)

[[ 96   8  18   4]
 [ 90   9  18   2]
 [102  10  18   3]
 [ 90   8  16   4]
 [105   9  19   2]]


### Comparing students 3 and 4 for best performer

In [ ]:
score_for_s3 = scaled_matrix_2[2, :]
score_for_s4 = scaled_matrix_2[3, :]

print(score_for_s3)
print(score_for_s4)


result = score_for_s3 - score_for_s4


result = np.where(result < 0, "student 4 performed better", "student 3 performed better")



for i in range(result.shape[0]):
   print(f'Subject {subjects[i]}:  {result}')




[102  10  18   3]
[90  8 16  4]
Subject maths:  ['student 3 performed better' 'student 3 performed better'
 'student 3 performed better' 'student 4 performed better']
Subject physics:  ['student 3 performed better' 'student 3 performed better'
 'student 3 performed better' 'student 4 performed better']
Subject yoruba:  ['student 3 performed better' 'student 3 performed better'
 'student 3 performed better' 'student 4 performed better']
Subject french:  ['student 3 performed better' 'student 3 performed better'
 'student 3 performed better' 'student 4 performed better']
