# Solution for Task 14: Matrix; using numpy


### Que: 1

matrix A =
\begin{bmatrix}
 2 & -1 \\
 0 & 3
\end{bmatrix}


matrix B = 
\begin{bmatrix}
 1 & -2 \\
 4 & 5
\end{bmatrix}

where scalers: c = 2 & d = 3;

### a.)

In [9]:
import numpy as np
import pandas as pd


matrix_A = np.array([[2, -1],
                      [0, 3]])

matrix_B = np.array([[2, -1],
                      [0, 3]])

c, d = 2, 3

cA = c * matrix_A

print("1.i. cA is give by:")
print(cA)

print("1.ii. dA is give by:")
dB = c * matrix_B
print(dB)

print("1.iii. (c+d)A is give by:")

print((c+d)* matrix_A)

1.i. cA is give by:
[[ 4 -2]
 [ 0  6]]
1.ii. dA is give by:
[[ 4 -2]
 [ 0  6]]
1.iii. (c+d)A is give by:
[[10 -5]
 [ 0 15]]


### 1b.

### 1c.

In [10]:
transpose_A = np.transpose(matrix_A)
transpose_B = np.transpose(matrix_B)

print("Transpose of A:\n", transpose_A)
print("Transpose of B:\n", transpose_B)

Transpose of A:
 [[ 2  0]
 [-1  3]]
Transpose of B:
 [[ 2  0]
 [-1  3]]


### 1d.

Checking Determinant for Invertibility:


In [12]:
print("Checking Determinant for Invertibility:")
det_A = np.linalg.det(matrix_A)
det_B = np.linalg.det(matrix_B)

print("Determinant of A:", det_A)
print("Determinant of B:", det_B)

# Check invertibility
if det_A != 0:
    inv_A = np.linalg.inv(matrix_A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix A is not invertible.")

if det_B != 0:
    inv_B = np.linalg.inv(matrix_B)
    print("Inverse of B:\n", inv_B)
else:
    print("Matrix B is not invertible.")

Checking Determinant for Invertibility:
Determinant of A: 6.0
Determinant of B: 6.0
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]
Inverse of B:
 [[0.5        0.16666667]
 [0.         0.33333333]]


### Finding the inverse of A and B:

In [14]:
print("Finding the inverse of A and B:")

inv_A = np.linalg.inv(matrix_A)
inv_B = np.linalg.inv(matrix_B)

print("Inverse of A:\n", inv_A)
print("Inverse of B:\n", inv_B)


Finding the inverse of A and B:
Inverse of A:
 [[0.5        0.16666667]
 [0.         0.33333333]]
Inverse of B:
 [[0.5        0.16666667]
 [0.         0.33333333]]
